-- Run this entire script in the Supabase SQL editor before ingestion.
-- Changes an EMPTY old table to 384 dimensions; never deletes existing rows.
begin;
create extension if not exists vector with schema extensions;
-- Existing projects may have pgvector in public instead of extensions.
set local search_path = public, extensions;
create table if not exists public.chunks (
    id bigint generated by default as identity primary key,
    doc_id text not null,
    chunk_index integer not null,
    content text not null,
    metadata jsonb not null default '{}'::jsonb,
    embedding vector(384) not null
);

lock table public.chunks in access exclusive mode;
do $$
declare
    embedding_type text;
    id_sequence text;
begin
    select format_type(atttypid, atttypmod) into embedding_type
    from pg_attribute
    where attrelid = 'public.chunks'::regclass
      and attname = 'embedding' and not attisdropped;
    if embedding_type is null then
        raise exception 'public.chunks has no embedding column; check its schema';
    end if;
    if embedding_type not in ('vector(384)', 'public.vector(384)', 'extensions.vector(384)') then
        if exists (select 1 from public.chunks) then
            raise exception 'Cannot convert populated chunks to vector(384). Back up and re-embed documents first.';
        end if;
        alter table public.chunks alter column embedding
            type vector(384) using embedding::vector(384);
    end if;
    id_sequence := pg_get_serial_sequence('public.chunks', 'id');
    if id_sequence is not null then
        execute format('grant usage, select on sequence %s to service_role', id_sequence);
    end if;
end $$;

alter table public.chunks enable row level security;
grant usage on schema public to service_role;
grant select, insert, delete on public.chunks to service_role;

-- Separate name preserves any existing search function for the previous model.
create or replace function public.match_chunks_bge(
    query_embedding vector(384),
    match_count integer default 5,
    filter jsonb default '{}'::jsonb
) returns table (
    id bigint, doc_id text, chunk_index integer, content text,
    metadata jsonb, similarity double precision
)
language sql stable security invoker
set search_path = public, extensions
as $$
    select c.id, c.doc_id, c.chunk_index, c.content, c.metadata,
           1 - (c.embedding <=> query_embedding) as similarity
    from public.chunks c
    where c.metadata @> filter
      and c.metadata->>'embedding_model' = 'BAAI/bge-small-en-v1.5'
    order by c.embedding <=> query_embedding
    limit greatest(match_count, 0);
$$;
revoke execute on function public.match_chunks_bge(vector, integer, jsonb) from public;
grant execute on function public.match_chunks_bge(vector, integer, jsonb) to service_role;
notify pgrst, 'reload schema';
commit;
